# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

pod 'UIWindows', :git => 'https://github.com/sinLuke/UIWindows.git'

target 'ExampleForUIWindows' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleForUIWindows

end
